### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asdf@asdf.com",
  "password": "asdlfkajsd"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/0

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "password": "aaaaa"
}






















### List all messages

GET http://localhost:3000/messages


### Create new message
POST http://localhost:3000/messages
Content-Type: application/json

{
  "content": "hi nitesh."
}


### Get single message
GET http://localhost:3000/messages/1502


### Testing dependency injection b/w modules
GET http://localhost:3000/computer